#!/bin/bash

### This script is called after the user upgrades the application.

set -e

export PATH=/var/apps/python312/target/bin:$PATH

VENV_DIR="${TRIM_PKGVAR}/.venv"
APP_DIR="${TRIM_APPDEST}"
SERVER_DIR="${APP_DIR}/server"

if [ ! -x "${VENV_DIR}/bin/python" ]; then
    python3 -m venv "${VENV_DIR}"
fi

"${VENV_DIR}/bin/pip" install --no-index --find-links "${SERVER_DIR}/wheels" -r "${SERVER_DIR}/requirements.txt"

exit 0
